### ISSUE TITLE
Separate doc for contributing guidelines

### ISSUE THREAD

**Issue by andy5995** [DukkhaLess/DukkhaLessClient#18]
I'd suggest separating the `contributing` section of the README into its own document.

Besides, ISSUE_TEMPLATE the COC, GitHub can utilize a CONTRIBUTING.md document. 

One of the places it shows up to guide the user is on the "new ticket" page. You can see an example here (note the lower-right corner, the link to "contributing"):

https://github.com/theimpossibleastronaut/rmw/issues/new

**Comment by AlexaDeWit** [comment]
Thanks Andy, and I'm sorry I never noticed you created this issue.

This will be closed by #19 since that' basically my development branch.

**Comment by AlexaDeWit** [comment]
Ah, I see. I wasn't watching the repo. That's fixed now :D

**Comment by andy5995** [comment]
Ok :)
